name: Check PR Branch Up-to-Date

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  check-up-to-date:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v3

      # Fetch all branches
      - name: Fetch all branches
        run: git fetch origin main

      # Compare PR branch with main
      - name: Check if branch is up-to-date with main
        run: |
          git checkout ${{ github.event.pull_request.head.ref }}
          git fetch origin main
          git merge-base --is-ancestor origin/main HEAD || exit 1
        shell: bash

      # Mark as failed if not up-to-date
      - name: Report result
        if: failure()
        run: echo "The pull request branch is not up-to-date with main. Please rebase or merge main into your branch."
